### PR TITLE
Fix Bug with Mentor Search

### LINKED ISSUE #321: bug: Fix mentors Format Filter
### Describe the bug
On mentor search there is a filter for format, if you select both it only shows mentors with type both, does not show mentors that are ad-hoc only or long-term only. That is not the expectation. 

### To Reproduce
1. Go to Mentors Page
2. Click on `Advanced Filters` 
3. Click on `Format` 
4. Select `Ad-hoc` 

### Expected behavior
* Selecting Ad-hoc should return mentors that are `Ad-hoc` or `both`
* Selecting Long-term should return mentors that are `Long-term` or `both`
* Both could be removed as a filter (because it is the default behaviour)

### Screenshots
image

### PR DESCRIPTION
**Pull request by khairahscorner**
## Description
- fixes #321 
- updates filtering logic for search by mentoring format type
- fixes: mentors with spellings like "Both" (instead of "both") were not properly displayed as "Long term relationship and Ad-hoc"

## Change Type
- [x] Bug Fix
- [ ] New Feature
- [ ] Code Refactor
- [ ] Mentor Update
- [ ] Documentation
- [ ] Other

## Related Issue

#321 

## Screenshots

Screenshot 2024-04-14 at 8 50 33 am
Screenshot 2024-04-14 at 9 54 48 am

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] I checked and followed the [contributor guide](CONTRIBUTING.md) 
- [x] I have tested my changes locally.
- [x] I have added a screenshot from the website after I tested it locally

### CODE REVIEW

File: assets/js/search.js [hunk 1]
```diff
@@ -1,15 +1,18 @@
 let controllerSearch = (function(jQuery) {
+    const COMMON_MENTOR_TYPE = "both";
```
Comment (mads6879) [inline assets/js/search.js:2]: Nothing wrong with the name as such but would it be more meaningful if it was called **MENTOR_TYPE_BOTH** since we are using it later in a IF condition (#161)

File: e2e-tests/cypress/support/locators/mentors_page/mentors_page.locate.js [hunk 2]
```diff
@@ -244,6 +244,10 @@ class mentorsLocatorManager {
     let mentoringTypeDisplayed =
       mentoringTypes === 'both'
         ? 'Long term relationship and Ad-Hoc'
+        : mentoringTypes === 'long-term'
+        ? 'Long term relationship'
```
Comment (mads6879) [inline e2e-tests/cypress/support/locators/mentors_page/mentors_page.locate.js:248]: Defining and using constants will make the code easy to maintain. Also strings are prone to typos so using constants avoids that.
e.g. MENTOR_TYPE_LONG_TERM, MENTOR_TYPE_ADHOC and MENTOR_TYPE_BOTH.

**Review by mads6879 — APPROVED** [review]

File: assets/js/search.js (hunk 1 above)
Comment (khairahscorner) [reply assets/js/search.js:2]: sounds much better✅

**Review by dricazenck — APPROVED** [review]
Amazing!! Thanks for the quick fixes ❤️
